### PR TITLE
Update dependencies and PHP version

### LINKED ISSUE #12: Carbon 2
Are there any plans to move to usinf `nesbot/carbon` v2 ?

I am unable to install other packages because of this conflict.

### PR DESCRIPTION
**Pull request by rosswintle**
This PR:
 - updates the dependencies (in particular Carbon v2) - resolves #12 
 - updates the required PHP version to 7.3 (as required by Carbon v2.0 and PHPUnit v9.0)
 - adds WPCS and PHPStan
 - prepares for submission to packagist.org as deliciousbrains/wp-queue 

All tests pass

There are some PHPCS and PHPStan fails that are not critical and will mostly need manual fixing.

## Testing

A code review should show there's no functional changes. You can:

1. Run `./vendor/bin/phpunit`
2. Run `./vendor/bin/phpstan analyze` (there will be errors, but nothing that affects functionality)

### CODE REVIEW

**Comment by rosswintle** [comment]
@polevaultweb Do you want to review this `wp-queue` update? Or are you happy for one of the team to do it?

None of the code has changed. It's all dependencies, code formatting and some type hints.

I'll tag a v2.0 once we're happy (as I've bumped the minimum PHP version) and add to packagist as `deliciousbrains/wp-queue`.

This shouldn't break anything for anyone. The only possibility for users is dependency conflicts, which will be reported by composer.

**Comment by polevaultweb** [comment]
@rosswintle yes please get one of the team to review and test

**Comment by rosswintle** [comment]
@mauryaratan Can you take a look at this please? I'm trying to work through updating a bunch of dependencies for our sites and this is something we use.

**Review by mauryaratan — APPROVED** [review]
LGTM 🚀

**Pull request merged**
